
development:
  adapter: postgresql
  encoding: unicode
  database: scoutpost_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: scoutpost_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: scoutpost_production
  pool: 5
